import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import DisplayNavBar from "@/components/NavBar/DisplayNavBar";
import { ControlDisplayProvider } from "@/context/ControlDisplay";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ES">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <ControlDisplayProvider>
          <DisplayNavBar />
          {children}
        </ControlDisplayProvider>
      </body>
    </html>
  );
}
